class FirestoreCollections {
  const FirestoreCollections._();

  static const users = 'users';
  static const roleCorrectionRequests = 'role_correction_requests';
  static const roleAuditLogs = 'role_audit_logs';
  static const adminAuditLogs = 'admin_audit_logs';
  static const colleges = 'colleges';
  static const departments = 'departments';
  static const courses = 'courses';
  static const assessments = 'assessments';
  static const assessmentFeedback = 'assessment_feedback';
  static const moods = 'moods';
  static const appointments = 'appointments';
  static const appointmentHistory = 'history';
  static const notifications = 'notifications';
  static const userDevices = 'user_devices';
  static const analyticsDaily = 'analytics_daily';
  static const analyticsEvents = '_analytics_events';
  static const inquiries = 'inquiries';
  static const recommendations = 'recommendations';
  static const reports = 'reports';
  static const insightCategories = 'insight_categories';
  static const insightContent = 'insight_content';
  static const insightRules = 'insight_rules';
  static const adminStatusSummaries = 'admin_status_summaries';
  static const userActivities = 'user_activities';
  static const breathingSessions = 'breathing_sessions';
  static const sleepEntries = 'sleep_entries';
  static const sleepPreferences = 'sleep_preferences';
  static const sleepSharedSummaries = 'sleep_shared_summaries';
  static const activeCounselorAssignments = 'active_counselor_assignments';
  static const secretChats = 'secret_chats';
  static const secretChatComments = 'secret_chat_comments';
  static const secretChatInteractions = 'secret_chat_interactions';
  static const secretChatProfiles = 'secret_chat_profiles';
  static const secretChatAliases = 'secret_chat_aliases';
  static const secretChatProfileStats = 'secret_chat_profile_stats';
  static const secretChatEvents = '_secret_chat_events';
  static const mindAidMessages = 'mind_aid_messages';
  static const mindAidPreferences = 'mind_aid_preferences';
  static const mindAidFeedback = 'mind_aid_feedback';
  static const mindAidAnalyticsDaily = 'mind_aid_analytics_daily';
}
