name: mind_mates
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.12.0

dependencies:
  camera: ^0.12.0+1
  cloud_firestore: ^6.6.0
  cloud_functions: ^6.3.3
  firebase_auth: ^6.5.4
  firebase_app_check: ^0.4.5
  firebase_core: ^4.11.0
  firebase_messaging: ^16.1.1
  firebase_remote_config: ^6.2.0
  firebase_storage: ^13.4.3
  flutter:
    sdk: flutter
  http: ^1.6.0
  image: ^4.9.1
  image_picker: ^1.2.3
  just_audio: ^0.10.6
  permission_handler: ^12.0.3
  provider: ^6.1.5+1
  share_plus: ^10.1.4
  flutter_secure_storage: ^9.2.4

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/Login/
    - assets/images/Create Account/
    - assets/images/ONBOARDING_1/
    - assets/images/ONBOARDING_2/
    - assets/images/ONBOARDING_3/
    - assets/images/ONBOARDING_4/ONBOARDING 4/
    - assets/images/DASHBOARD/
    - assets/images/SERVICES/
    - assets/images/MESSAGE/
    - assets/images/PROFILE 1/
    - assets/images/INSIGHTS/
    - assets/images/SECRET CHAT/
    - assets/images/Quick assesment/ENTER NAME/
    - assets/images/Quick assesment/QUESTION 1/
    - assets/images/Quick assesment/QUESTION 2/
    - assets/images/Quick assesment/QUESTION 3/
    - assets/images/Quick assesment/QUESTION 4/
    - assets/images/Quick assesment/QUESTION 5/
    - assets/data/mind_aid/
    - assets/audio/breathing/
