const insightSeedCategories = [
  {
    'id': 'stress_burnout',
    'label': 'Stress relief',
    'icon': 'stress',
    'sortOrder': 1,
    'isDefaultSelected': false,
    'isActive': true,
  },
  {
    'id': 'anxiety',
    'label': 'Manage anxiety',
    'icon': 'anxiety',
    'sortOrder': 2,
    'isDefaultSelected': false,
    'isActive': true,
  },
  {
    'id': 'emotional_wellbeing',
    'label': 'Emotions',
    'icon': 'mood',
    'sortOrder': 3,
    'isDefaultSelected': false,
    'isActive': true,
  },
  {
    'id': 'sleep_mental_health',
    'label': 'Better sleep',
    'icon': 'sleep',
    'sortOrder': 4,
    'isDefaultSelected': true,
    'isActive': true,
  },
  {
    'id': 'self_esteem_confidence',
    'label': 'Confidence',
    'icon': 'mood',
    'sortOrder': 5,
    'isDefaultSelected': false,
    'isActive': true,
  },
  {
    'id': 'depression_support',
    'label': 'Low mood',
    'icon': 'mood',
    'sortOrder': 6,
    'isDefaultSelected': false,
    'isActive': true,
  },
];

const insightSeedContent = [
  {
    'id': 'weekly_patterns_intro',
    'title': 'Understanding your wellness patterns',
    'subtitle': 'See how check-ins, assessments, and habits connect.',
    'categoryId': 'emotional_wellbeing',
    'categoryLabel': 'Your data',
    'sectionId': 'patterns',
    'imageAsset': '',
    'publishedAt': '2026-07-01',
    'sortOrder': 0,
    'isActive': true,
    'contentType': 'pattern',
    'tags': ['patterns', 'mood tracking', 'assessment'],
    'source': 'MindMate',
    'body':
        'Your mood logs, assessments, breathing sessions, and support activity can become weekly patterns. These patterns help MindMate recommend more relevant wellness content over time.',
  },
  {
    'id': 'understanding_stress',
    'title': 'What is stress?',
    'subtitle': 'Understand signs, symptoms, and healthy first steps.',
    'categoryId': 'stress_burnout',
    'categoryLabel': 'Stress relief',
    'sectionId': 'wellbeing_101',
    'imageAsset': 'assets/images/INSIGHTS/Frame 13.png',
    'publishedAt': '2026-07-01',
    'sortOrder': 1,
    'isActive': true,
    'contentType': 'article',
    'tags': ['stress', 'burnout', 'pacc'],
    'source': 'Mental Health Insights Categories.docx',
    'body':
        'Stress is the body natural response to challenges. Small amounts can help with focus, but long-term stress can affect physical, emotional, and mental well-being. Healthy steps include rest, movement, sleep, social support, and talking to PACC when stress affects daily life.',
  },
  {
    'id': 'academic_stress',
    'title': 'Academic stress: how to manage it',
    'subtitle': 'Plan workloads, reduce overload, and know when to ask help.',
    'categoryId': 'stress_burnout',
    'categoryLabel': 'Academic',
    'sectionId': 'latest',
    'imageAsset': 'assets/images/INSIGHTS/Frame 15.png',
    'publishedAt': '2026-07-02',
    'sortOrder': 2,
    'isActive': true,
    'contentType': 'article',
    'tags': ['academic stress', 'stress', 'student'],
    'source': 'Mental Health Insights Categories.docx',
    'body':
        'College stress can come from deadlines, exams, poor time management, burnout, and unhealthy coping habits. Break large tasks into smaller goals, use a realistic schedule, take breaks, and visit PACC when stress affects study, sleep, or daily life.',
  },
  {
    'id': 'burnout_recovery',
    'title': 'Burnout: causes, symptoms, and recovery',
    'subtitle': 'Notice exhaustion early and rebuild healthier routines.',
    'categoryId': 'stress_burnout',
    'categoryLabel': 'Burnout',
    'sectionId': 'recommended',
    'imageAsset': 'assets/images/INSIGHTS/Frame 13.png',
    'publishedAt': '2026-07-03',
    'sortOrder': 3,
    'isActive': true,
    'contentType': 'article',
    'tags': ['burnout', 'stress', 'support'],
    'source': 'Mental Health Insights Categories.docx',
    'body':
        'Burnout is physical, mental, and emotional exhaustion from prolonged stress. It can show as fatigue, low motivation, difficulty concentrating, irritability, and withdrawal. Recovery starts with rest, realistic goals, support, counseling, and consistent self-care.',
  },
  {
    'id': 'healthy_stress_reduction',
    'title': 'Healthy ways to reduce stress',
    'subtitle': 'Simple habits that support calm and balance.',
    'categoryId': 'stress_burnout',
    'categoryLabel': 'Self-care',
    'sectionId': 'wellbeing_101',
    'imageAsset': 'assets/images/INSIGHTS/Frame 14.png',
    'publishedAt': '2026-07-04',
    'sortOrder': 4,
    'isActive': true,
    'contentType': 'article',
    'tags': ['stress', 'breathing', 'mindfulness'],
    'source': 'Mental Health Insights Categories.docx',
    'body':
        'Stress can be reduced through physical activity, balanced meals, relaxation, enjoyable activities, trusted conversations, time management, sleep, and professional support when stress continues to affect school, work, or relationships.',
  },
  {
    'id': 'understanding_anxiety',
    'title': 'Understanding anxiety',
    'subtitle': 'Learn what anxiety is and how to notice triggers.',
    'categoryId': 'anxiety',
    'categoryLabel': 'Anxiety',
    'sectionId': 'wellbeing_101',
    'imageAsset': 'assets/images/INSIGHTS/Frame 15.png',
    'publishedAt': '2026-07-05',
    'sortOrder': 5,
    'isActive': true,
    'contentType': 'article',
    'tags': ['anxiety', 'stress', 'triggers'],
    'source': '4_LIKHAAA.docx',
    'body':
        'Anxiety can include apprehension, muscle tension, faster breathing, and a racing heartbeat. Helpful steps include identifying triggers, staying physically active, eating well, learning about anxiety, and seeking PACC support when anxiety feels hard to control.',
  },
  {
    'id': 'normal_worry_vs_anxiety',
    'title': 'Normal worry vs anxiety disorder',
    'subtitle': 'Know when worry becomes disruptive.',
    'categoryId': 'anxiety',
    'categoryLabel': 'Anxiety',
    'sectionId': 'latest',
    'imageAsset': 'assets/images/INSIGHTS/Frame 15.png',
    'publishedAt': '2026-07-06',
    'sortOrder': 6,
    'isActive': true,
    'contentType': 'article',
    'tags': ['anxiety', 'worry', 'sleep'],
    'source': '4_LIKHAAA.docx',
    'body':
        'Worry is usually short-lived and connected to a realistic concern. Anxiety disorder may involve excessive worry lasting weeks or months and disrupting focus, sleep, and daily activities. Healthy routines, sleep, relaxation, and counseling can help.',
  },
  {
    'id': 'anxiety_triggers',
    'title': 'Common triggers of anxiety',
    'subtitle': 'Academic, financial, social, health, and sleep triggers.',
    'categoryId': 'anxiety',
    'categoryLabel': 'Anxiety',
    'sectionId': 'recommended',
    'imageAsset': 'assets/images/INSIGHTS/Group 1383.png',
    'publishedAt': '2026-07-07',
    'sortOrder': 7,
    'isActive': true,
    'contentType': 'article',
    'tags': ['anxiety', 'academic stress', 'sleep'],
    'source': '4_LIKHAAA.docx',
    'body':
        'Anxiety can be triggered by school or work pressure, financial problems, relationship conflict, major life changes, health concerns, social situations, and lack of sleep. Tracking triggers helps you choose support strategies earlier.',
  },
  {
    'id': 'breathing_relaxation',
    'title': 'Breathing and relaxation techniques',
    'subtitle': 'Calm your mind and body with simple practices.',
    'categoryId': 'anxiety',
    'categoryLabel': 'Mindfulness',
    'sectionId': 'recommended',
    'imageAsset': 'assets/images/INSIGHTS/Frame 14.png',
    'publishedAt': '2026-07-08',
    'sortOrder': 8,
    'isActive': true,
    'contentType': 'article',
    'tags': ['anxiety', 'breathing', 'stress'],
    'source': '4_LIKHAAA.docx',
    'body':
        'Relaxation can reduce stress and physical anxiety symptoms. Try slow breathing, mindfulness meditation, progressive muscle relaxation, gentle exercise, or grounding techniques to support focus, sleep, and emotional balance.',
  },
  {
    'id': 'understanding_depression',
    'title': 'Understanding depression',
    'subtitle': 'Recognize low mood and know when to seek support.',
    'categoryId': 'depression_support',
    'categoryLabel': 'Low mood',
    'sectionId': 'wellbeing_101',
    'imageAsset': 'assets/images/INSIGHTS/Group 1383.png',
    'publishedAt': '2026-07-09',
    'sortOrder': 9,
    'isActive': true,
    'contentType': 'article',
    'tags': ['depression', 'low mood', 'pacc'],
    'source': '4_LIKHAAA.docx',
    'body':
        'Depression is more than temporary sadness. It can affect emotions, thoughts, behavior, sleep, appetite, energy, concentration, and relationships. Visit PACC if sadness lasts more than two weeks or affects school, work, or daily life.',
  },
  {
    'id': 'depression_warning_signs',
    'title': 'Signs you should never ignore',
    'subtitle': 'Warning signs that deserve early support.',
    'categoryId': 'depression_support',
    'categoryLabel': 'Low mood',
    'sectionId': 'recommended',
    'imageAsset': 'assets/images/INSIGHTS/Group 1383.png',
    'publishedAt': '2026-07-10',
    'sortOrder': 10,
    'isActive': true,
    'contentType': 'article',
    'tags': ['depression', 'low mood', 'support'],
    'source': '4_LIKHAAA.docx',
    'body':
        'Warning signs include feeling sad or hopeless most days, losing interest, major sleep or appetite changes, difficulty concentrating, feeling worthless, withdrawing from others, constant fatigue, or declining performance.',
  },
  {
    'id': 'healthy_coping_depression',
    'title': 'Healthy coping strategies',
    'subtitle': 'Small routines that can support recovery.',
    'categoryId': 'depression_support',
    'categoryLabel': 'Self-care',
    'sectionId': 'latest',
    'imageAsset': 'assets/images/INSIGHTS/Frame 16.png',
    'publishedAt': '2026-07-11',
    'sortOrder': 11,
    'isActive': true,
    'contentType': 'article',
    'tags': ['depression', 'mood tracking', 'support'],
    'source': '4_LIKHAAA.docx',
    'body':
        'Healthy coping includes physical activity, regular sleep, balanced meals, supportive relationships, mindfulness, realistic daily goals, hobbies, and counseling. Avoid isolation, substance use, ignoring emotions, and overworking.',
  },
  {
    'id': 'understanding_emotions',
    'title': 'Understanding your emotions',
    'subtitle': 'Name, accept, and respond to feelings in healthy ways.',
    'categoryId': 'emotional_wellbeing',
    'categoryLabel': 'Emotions',
    'sectionId': 'wellbeing_101',
    'imageAsset': 'assets/images/INSIGHTS/Frame 16.png',
    'publishedAt': '2026-07-12',
    'sortOrder': 12,
    'isActive': true,
    'contentType': 'article',
    'tags': ['emotions', 'self-awareness', 'mood tracking'],
    'source': 'Mental Health Insights Categories.docx',
    'body':
        'Emotions help you understand experiences and make decisions. Naming feelings, accepting emotions as normal, reflecting on causes, expressing yourself safely, and talking to someone trusted can improve self-awareness and relationships.',
  },
  {
    'id': 'emotional_resilience',
    'title': 'How to build emotional resilience',
    'subtitle': 'Recover from difficult experiences and keep moving.',
    'categoryId': 'emotional_wellbeing',
    'categoryLabel': 'Resilience',
    'sectionId': 'recommended',
    'imageAsset': 'assets/images/INSIGHTS/Frame 16.png',
    'publishedAt': '2026-07-13',
    'sortOrder': 13,
    'isActive': true,
    'contentType': 'article',
    'tags': ['resilience', 'stress', 'emotions'],
    'source': 'Mental Health Insights Categories.docx',
    'body':
        'Emotional resilience is the ability to adapt, recover, and grow after stress or difficulty. Build it through positive relationships, healthy coping skills, focusing on what you can control, learning from challenges, and caring for mental and physical health.',
  },
  {
    'id': 'anger_frustration',
    'title': 'Managing anger and frustration',
    'subtitle': 'Pause, breathe, and express anger respectfully.',
    'categoryId': 'emotional_wellbeing',
    'categoryLabel': 'Emotions',
    'sectionId': 'latest',
    'imageAsset': 'assets/images/INSIGHTS/Frame 16.png',
    'publishedAt': '2026-07-14',
    'sortOrder': 14,
    'isActive': true,
    'contentType': 'article',
    'tags': ['anger', 'emotions', 'support'],
    'source': 'Mental Health Insights Categories.docx',
    'body':
        'Anger is normal, but it should be expressed in healthy ways. Take deep breaths, pause before reacting, exercise, or talk to someone trusted. Seek support if anger affects relationships, school, or daily life.',
  },
  {
    'id': 'self_compassion',
    'title': 'Practicing self-compassion',
    'subtitle': 'Treat yourself with kindness during hard moments.',
    'categoryId': 'emotional_wellbeing',
    'categoryLabel': 'Self-care',
    'sectionId': 'recommended',
    'imageAsset': 'assets/images/INSIGHTS/Frame 16.png',
    'publishedAt': '2026-07-15',
    'sortOrder': 15,
    'isActive': true,
    'contentType': 'article',
    'tags': ['self-compassion', 'confidence', 'emotions'],
    'source': 'Mental Health Insights Categories.docx',
    'body':
        'Self-compassion means responding to yourself with kindness instead of harsh criticism. Speak kindly to yourself, accept imperfections, celebrate small wins, take breaks, and practice gratitude.',
  },
  {
    'id': 'building_self_confidence',
    'title': 'Building self-confidence',
    'subtitle': 'Strengthen trust in your abilities and potential.',
    'categoryId': 'self_esteem_confidence',
    'categoryLabel': 'Confidence',
    'sectionId': 'wellbeing_101',
    'imageAsset': 'assets/images/INSIGHTS/Group 1463.png',
    'publishedAt': '2026-07-16',
    'sortOrder': 16,
    'isActive': true,
    'contentType': 'article',
    'tags': ['confidence', 'self-esteem', 'growth'],
    'source': 'Mental Health Insights Categories.docx',
    'body':
        'Self-confidence is believing in your abilities, strengths, and potential. Build confidence by setting realistic goals, learning new skills, celebrating achievements, practicing positive thinking, and asking support when self-doubt feels heavy.',
  },
  {
    'id': 'negative_self_talk',
    'title': 'Overcoming negative self-talk',
    'subtitle': 'Replace harsh thoughts with realistic encouragement.',
    'categoryId': 'self_esteem_confidence',
    'categoryLabel': 'Confidence',
    'sectionId': 'recommended',
    'imageAsset': 'assets/images/INSIGHTS/Group 1463.png',
    'publishedAt': '2026-07-17',
    'sortOrder': 17,
    'isActive': true,
    'contentType': 'article',
    'tags': ['confidence', 'anxiety', 'self-esteem'],
    'source': 'Mental Health Insights Categories.docx',
    'body':
        'Negative self-talk is the habit of criticizing yourself or expecting the worst. Challenge negative thoughts, focus on strengths, practice affirmations, and treat yourself with kindness to support confidence and emotional well-being.',
  },
  {
    'id': 'growth_mindset',
    'title': 'Developing a growth mindset',
    'subtitle': 'Use mistakes as chances to learn and grow.',
    'categoryId': 'self_esteem_confidence',
    'categoryLabel': 'Growth',
    'sectionId': 'latest',
    'imageAsset': 'assets/images/INSIGHTS/Group 1463.png',
    'publishedAt': '2026-07-18',
    'sortOrder': 18,
    'isActive': true,
    'contentType': 'article',
    'tags': ['confidence', 'resilience', 'growth'],
    'source': 'Mental Health Insights Categories.docx',
    'body':
        'A growth mindset means believing abilities can improve through effort, learning, and practice. Learn from mistakes, accept challenges, keep practicing, ask feedback, and stay patient with progress.',
  },
  {
    'id': 'why_sleep_matters',
    'title': 'Why sleep matters',
    'subtitle': 'Sleep supports mood, focus, memory, and recovery.',
    'categoryId': 'sleep_mental_health',
    'categoryLabel': 'Sleep',
    'sectionId': 'wellbeing_101',
    'imageAsset': 'assets/images/INSIGHTS/Group 1463.png',
    'publishedAt': '2026-07-19',
    'sortOrder': 19,
    'isActive': true,
    'contentType': 'article',
    'tags': ['sleep', 'mood', 'stress'],
    'source': 'Mental Health Insights Categories.docx',
    'body':
        'Sleep helps the brain and body recover. Quality sleep improves concentration, learning, emotional balance, energy, memory, and physical health. Poor sleep can make stress and mood concerns harder to manage.',
  },
  {
    'id': 'sleep_emotional_health',
    'title': 'Sleep problems and emotional health',
    'subtitle': 'Understand the cycle between poor sleep and emotions.',
    'categoryId': 'sleep_mental_health',
    'categoryLabel': 'Sleep',
    'sectionId': 'recommended',
    'imageAsset': 'assets/images/INSIGHTS/Group 1463.png',
    'publishedAt': '2026-07-20',
    'sortOrder': 20,
    'isActive': true,
    'contentType': 'article',
    'tags': ['sleep', 'anxiety', 'depression'],
    'source': 'Mental Health Insights Categories.docx',
    'body':
        'Poor sleep can increase stress, anxiety, irritability, and difficulty concentrating. Emotional stress can also make sleep harder, creating a cycle. Seek support if sleep problems continue for weeks or affect studies or daily life.',
  },
  {
    'id': 'better_sleep_tips',
    'title': 'Tips for better sleep',
    'subtitle': 'Build sleep habits that support mental health.',
    'categoryId': 'sleep_mental_health',
    'categoryLabel': 'Sleep',
    'sectionId': 'latest',
    'imageAsset': 'assets/images/INSIGHTS/Group 1463.png',
    'publishedAt': '2026-07-21',
    'sortOrder': 21,
    'isActive': true,
    'contentType': 'article',
    'tags': ['sleep', 'routine', 'self-care'],
    'source': 'Mental Health Insights Categories.docx',
    'body':
        'Sleep habits include sleeping and waking at consistent times, avoiding caffeine before bedtime, limiting screen time before sleep, creating a quiet comfortable room, and relaxing before bed.',
  },
  {
    'id': 'sleep_hygiene',
    'title': 'Sleep hygiene guide',
    'subtitle': 'Daily practices that promote quality sleep.',
    'categoryId': 'sleep_mental_health',
    'categoryLabel': 'Sleep',
    'sectionId': 'recommended',
    'imageAsset': 'assets/images/INSIGHTS/Group 1463.png',
    'publishedAt': '2026-07-22',
    'sortOrder': 22,
    'isActive': true,
    'contentType': 'article',
    'tags': ['sleep', 'sleep hygiene', 'stress'],
    'source': 'Mental Health Insights Categories.docx',
    'body':
        'Sleep hygiene means routines and environments that support healthy sleep. Keep your bedroom comfortable, avoid heavy meals before bedtime, exercise regularly, limit naps, and keep a consistent bedtime routine.',
  },
  {
    'id': 'when_to_consult_pacc',
    'title': 'When to consult a counselor',
    'subtitle': 'Know when PACC support may be helpful.',
    'categoryId': 'stress_burnout',
    'categoryLabel': 'PACC support',
    'sectionId': 'recommended',
    'imageAsset': 'assets/images/INSIGHTS/Group 1383.png',
    'publishedAt': '2026-07-23',
    'sortOrder': 23,
    'isActive': true,
    'contentType': 'support',
    'tags': ['pacc', 'support', 'counseling'],
    'source': '4_LIKHAAA.docx',
    'body':
        'Consider visiting PACC if stress, anxiety, sadness, burnout, sleep problems, or emotional concerns persist and affect school, work, relationships, or daily life. PACC can provide assessment, counseling, follow-up, referrals, and mental health programs.',
  },
  {
    'id': 'mood_check_in',
    'title': 'Start with a mood check-in',
    'subtitle': 'Track patterns so support can become more personal.',
    'categoryId': 'emotional_wellbeing',
    'categoryLabel': 'Your data',
    'sectionId': 'recommended',
    'imageAsset': '',
    'publishedAt': '2026-07-24',
    'sortOrder': 24,
    'isActive': true,
    'contentType': 'action',
    'tags': ['mood tracking', 'check-in', 'patterns'],
    'source': 'MindMate',
    'body':
        'Mood check-ins help build a clearer picture of your weekly mental wellness patterns. Even a short daily log can make recommendations more relevant.',
  },
];

const insightSeedRules = [
  {
    'id': 'sleep_focus_sleep_article',
    'contentId': 'sleep_emotional_health',
    'priority': 1,
    'matchType': 'any',
    'conditions': {
      'topConcernAreas': ['Sleep and Rest'],
    },
    'isActive': true,
  },
  {
    'id': 'sleep_focus_hygiene',
    'contentId': 'sleep_hygiene',
    'priority': 2,
    'matchType': 'any',
    'conditions': {
      'topConcernAreas': ['Sleep and Rest'],
    },
    'isActive': true,
  },
  {
    'id': 'stress_focus_burnout',
    'contentId': 'burnout_recovery',
    'priority': 3,
    'matchType': 'any',
    'conditions': {
      'topConcernAreas': ['Academic Stress', 'Workplace Stress'],
    },
    'isActive': true,
  },
  {
    'id': 'stress_focus_relaxation',
    'contentId': 'breathing_relaxation',
    'priority': 4,
    'matchType': 'any',
    'conditions': {
      'topConcernAreas': ['Academic Stress', 'Workplace Stress'],
      'breathingSessionMax': 0,
    },
    'isActive': true,
  },
  {
    'id': 'moderate_or_severe_support',
    'contentId': 'when_to_consult_pacc',
    'priority': 5,
    'matchType': 'any',
    'conditions': {
      'mentalStatus': ['moderate', 'severe'],
      'fullAssessmentStatus': ['High Concern', 'Very High Concern'],
    },
    'isActive': true,
  },
  {
    'id': 'anxiety_signal',
    'contentId': 'understanding_anxiety',
    'priority': 6,
    'matchType': 'any',
    'conditions': {
      'quickAssessmentSignal': ['watchful', 'elevated', 'highSupport'],
      'topConcernAreas': ['Emotional Well-Being'],
    },
    'isActive': true,
  },
  {
    'id': 'low_mood_support',
    'contentId': 'healthy_coping_depression',
    'priority': 7,
    'matchType': 'any',
    'conditions': {
      'averageMoodMax': 2.4,
      'topConcernAreas': ['Emotional Well-Being'],
    },
    'isActive': true,
  },
  {
    'id': 'no_mood_checkins',
    'contentId': 'mood_check_in',
    'priority': 8,
    'matchType': 'all',
    'conditions': {'moodCheckInMax': 0},
    'isActive': true,
  },
  {
    'id': 'no_breathing_sessions',
    'contentId': 'breathing_relaxation',
    'priority': 9,
    'matchType': 'all',
    'conditions': {'breathingSessionMax': 0},
    'isActive': true,
  },
  {
    'id': 'no_mindaid_messages',
    'contentId': 'when_to_consult_pacc',
    'priority': 10,
    'matchType': 'all',
    'conditions': {'mindAidMessageMax': 0},
    'isActive': true,
  },
];
