// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWCY8gfvXy3HKdN7u7nkNHWS5y7RZGGz0',
    appId: '1:842251480963:web:e03a5de3a6484757eb50b6',
    messagingSenderId: '842251480963',
    projectId: 'mind-mates-cd2cf',
    authDomain: 'mind-mates-cd2cf.firebaseapp.com',
    storageBucket: 'mind-mates-cd2cf.firebasestorage.app',
    measurementId: 'G-YD4S38H51E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAS2NzGcr6UsuaA06GSdVg_4Cm3GDR1YnA',
    appId: '1:842251480963:android:ed62272c31f74f2beb50b6',
    messagingSenderId: '842251480963',
    projectId: 'mind-mates-cd2cf',
    storageBucket: 'mind-mates-cd2cf.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC15o6ckV0LFEjTJD7PAZaVXUQvtHCZtIo',
    appId: '1:842251480963:ios:e21397ce5d424f8deb50b6',
    messagingSenderId: '842251480963',
    projectId: 'mind-mates-cd2cf',
    storageBucket: 'mind-mates-cd2cf.firebasestorage.app',
    androidClientId: '842251480963-66qdnfoc22jg8dc8n3h6nvshjl239ne0.apps.googleusercontent.com',
    iosClientId: '842251480963-dk3mb671q9c6dbqh1b236nvcaqbcvi03.apps.googleusercontent.com',
    iosBundleId: 'com.example.mindMates',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC15o6ckV0LFEjTJD7PAZaVXUQvtHCZtIo',
    appId: '1:842251480963:ios:e21397ce5d424f8deb50b6',
    messagingSenderId: '842251480963',
    projectId: 'mind-mates-cd2cf',
    storageBucket: 'mind-mates-cd2cf.firebasestorage.app',
    androidClientId: '842251480963-66qdnfoc22jg8dc8n3h6nvshjl239ne0.apps.googleusercontent.com',
    iosClientId: '842251480963-dk3mb671q9c6dbqh1b236nvcaqbcvi03.apps.googleusercontent.com',
    iosBundleId: 'com.example.mindMates',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWCY8gfvXy3HKdN7u7nkNHWS5y7RZGGz0',
    appId: '1:842251480963:web:2c4a1e0fabde9bf1eb50b6',
    messagingSenderId: '842251480963',
    projectId: 'mind-mates-cd2cf',
    authDomain: 'mind-mates-cd2cf.firebaseapp.com',
    storageBucket: 'mind-mates-cd2cf.firebasestorage.app',
    measurementId: 'G-X2ZW6KJ85L',
  );
}
